In [7]:
import json
import pandas as pd

In [8]:
# Load the JSON file
with open('simulated/results.json', 'r') as f:
    results = json.load(f)

# Flatten the JSON into a DataFrame
rows = []
for entry in results:
    algorithm = entry.get('algorithm')
    instance = entry.get('instance')
    output_mode = entry.get('outputMode')
    executions = entry.get('executions', [])
    for exec in executions:
        row = {
            'algorithm': algorithm,
            'instance': instance,
            'value': exec.get('value', None),
            'time': exec.get('time', None),
            'error': exec.get('error', None),
            #'errorMessage': exec.get('errorMessage', None),
        }
        # Add parameters if present
        params = exec.get('parameters', {})
        for k, v in params.items():
            row[k] = v
        rows.append(row)

df = pd.DataFrame(rows)
df['maxReservation'] = df['maxReservation'].astype('Int64')
df = df[df['error'] == False]
df = df.drop(columns=['error'])
df['value'] = df['value'] / 3600
df = df.sort_values(by='value', ascending=True)
display(df)

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
9227,C,instance-small-19,29.709481,25.654,1000,RANDOM,LOW_LOAD,RESERVATION_PER_SESSION,IGNORE_TREE_LEVEL,RANDOM,10,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
9650,C,instance-small-19,29.897334,231.940,1000,HIGH_LOAD,LOW_LOAD,RESERVATION_PER_SERVER,BOTTOM_TO_TOP,RANDOM,10,RANDOM,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
8472,C,instance-small-19,30.181037,1.416,1000,LOW_LOAD,HIGH_LOAD,RESERVATION_PER_SERVER,BOTTOM_TO_TOP,HIGH_LOAD,10,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
8789,C,instance-small-19,30.208403,20.625,1000,LOW_LOAD,ROUND_ROBIN,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,LOW_LOAD,10,LOW_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
8389,C,instance-small-19,30.208403,4.715,1000,LOW_LOAD,RANDOM,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,LOW_LOAD,10,LOW_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
875,C,instance-medium-15,647086.004267,59132.490,50,ROUND_ROBIN,HIGH_LOAD,RESERVATION_PER_SERVER,BOTTOM_TO_TOP,LOW_LOAD,20,ROUND_ROBIN,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
515,C,instance-medium-15,647118.858781,31415.251,50,ROUND_ROBIN,RANDOM,RESERVATION_PER_SESSION,IGNORE_TREE_LEVEL,HIGH_LOAD,10,HIGH_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
1263,C,instance-medium-15,670142.789790,71362.523,50,RANDOM,LOW_LOAD,RESERVATION_PER_SERVER,IGNORE_TREE_LEVEL,RANDOM,20,ROUND_ROBIN,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
675,C,instance-medium-15,916022.415359,56886.732,50,LOW_LOAD,LOW_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,RANDOM,20,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
906,C,instance-medium-15,995650.877921,76186.307,50,ROUND_ROBIN,LOW_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,RANDOM,20,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN

In [20]:
capacity = 1000
instance_type = 'small'
df = df[df['instance'].str.contains(instance_type)]
df_c = df[df['capacity'] == capacity]
df_c = df_c.drop(columns=['capacity'])
display(df_c)

,algorithm,instance,value,time,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
9227,C,instance-small-19,29.709481,25.654,RANDOM,LOW_LOAD,RESERVATION_PER_SESSION,IGNORE_TREE_LEVEL,RANDOM,10,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
9650,C,instance-small-19,29.897334,231.940,HIGH_LOAD,LOW_LOAD,RESERVATION_PER_SERVER,BOTTOM_TO_TOP,RANDOM,10,RANDOM,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
8472,C,instance-small-19,30.181037,1.416,LOW_LOAD,HIGH_LOAD,RESERVATION_PER_SERVER,BOTTOM_TO_TOP,HIGH_LOAD,10,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
8789,C,instance-small-19,30.208403,20.625,LOW_LOAD,ROUND_ROBIN,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,LOW_LOAD,10,LOW_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
8389,C,instance-small-19,30.208403,4.715,LOW_LOAD,RANDOM,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,LOW_LOAD,10,LOW_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10844,C,instance-small-17,811.593728,7.594,LOW_LOAD,RANDOM,RESERVATION_PER_SESSION,BOTTOM_TO_TOP,LOW_LOAD,250,HIGH_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
9884,C,instance-small-17,830.831364,18.024,ROUND_ROBIN,HIGH_LOAD,RESERVATION_PER_SESSION,IGNORE_TREE_LEVEL,LOW_LOAD,200,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
10198,C,instance-small-17,868.251076,9.752,LOW_LOAD,HIGH_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,HIGH_LOAD,250,HIGH_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
10618,C,instance-small-17,882.651476,17.354,RANDOM,HIGH_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,LOW_LOAD,200,HIGH_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
10920,C,instance-small-17,933.221406,2.796,RANDOM,LOW_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,RANDOM,150,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN

In [9]:
def show_best_times(df):
    best_times = df.groupby('instance').apply(lambda x: x.loc[x['value'].idxmin()]).reset_index(drop=True)
    return best_times

best_algorithms = show_best_times(df)
display(best_algorithms)

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,C,instance-medium-15,11393.694164,117.076,1000,RANDOM,LOW_LOAD,RESERVATION_PER_SERVER,IGNORE_TREE_LEVEL,LOW_LOAD,5,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
1,C,instance-medium-25,603.829964,7.035,1000,LOW_LOAD,HIGH_LOAD,RESERVATION_PER_SERVER,TOP_TO_BOTTOM,RANDOM,5,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
2,C,instance-small-17,283.498601,10.315,1000,LOW_LOAD,LOW_LOAD,RESERVATION_PER_SESSION,TOP_TO_BOTTOM,RANDOM,5,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
3,C,instance-small-19,29.709481,25.654,1000,RANDOM,LOW_LOAD,RESERVATION_PER_SESSION,IGNORE_TREE_LEVEL,RANDOM,10,HIGH_LOAD,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN

In [10]:
best_times_b = show_best_times(df[df['algorithm'] == 'B'])
display(best_times_b)

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,B,instance-medium-15,13331.107905,113.387,1000,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,IGNORE_TREE_LEVEL,BOTTOM_TO_TOP,HIGH_LOAD,HIGH_LOAD,NaN
1,B,instance-medium-25,719.258066,6.700,1000,NaN,NaN,NaN,NaN,NaN,5,NaN,NaN,BOTTOM_TO_TOP,TOP_TO_BOTTOM,RANDOM,ROUND_ROBIN,NaN
2,B,instance-small-17,371.792115,8.536,1000,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,TOP_TO_BOTTOM,HIGH_LOAD,HIGH_LOAD,NaN
3,B,instance-small-19,41.427904,10.901,1000,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,TOP_TO_BOTTOM,TOP_TO_BOTTOM,ROUND_ROBIN,ROUND_ROBIN,NaN

In [11]:
best_times_a = show_best_times(df[df['algorithm'] == 'A'])
display(best_times_a)

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,A,instance-medium-15,18395.169461,130.016,1000,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD
1,A,instance-medium-25,922.534027,7.945,1000,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD
2,A,instance-small-17,565.390404,3.000,1000,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD
3,A,instance-small-19,65.470351,1.051,1000,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD

In [13]:
capacity = 50
df_capacity = df[df['capacity'] == capacity]
display(show_best_times(df_capacity))
display(show_best_times(df_capacity[df_capacity['algorithm'] == 'C']))
display(show_best_times(df_capacity[df_capacity['algorithm'] == 'B']))
display(show_best_times(df_capacity[df_capacity['algorithm'] == 'A']))

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,B,instance-medium-15,223860.449368,912.341,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,BOTTOM_TO_TOP,ROUND_ROBIN,RANDOM,NaN
1,B,instance-medium-25,12782.286877,47.363,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,TOP_TO_BOTTOM,ROUND_ROBIN,ROUND_ROBIN,NaN
2,B,instance-small-17,5477.246625,55.715,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,IGNORE_TREE_LEVEL,HIGH_LOAD,ROUND_ROBIN,NaN
3,A,instance-small-19,544.553175,0.374,50,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,C,instance-medium-15,228958.271177,1598.879,50,RANDOM,HIGH_LOAD,RESERVATION_PER_SERVER,TOP_TO_BOTTOM,RANDOM,2,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN
1,C,instance-medium-25,13358.016101,88.036,50,RANDOM,RANDOM,RESERVATION_PER_SERVER,TOP_TO_BOTTOM,HIGH_LOAD,1,LOW_LOAD,IGNORE_TREE_LEVEL,NaN,NaN,NaN,NaN,NaN
2,C,instance-small-17,5843.113301,100.287,50,ROUND_ROBIN,ROUND_ROBIN,RESERVATION_PER_SERVER,TOP_TO_BOTTOM,HIGH_LOAD,1,RANDOM,BOTTOM_TO_TOP,NaN,NaN,NaN,NaN,NaN
3,C,instance-small-19,567.491891,16.809,50,LOW_LOAD,LOW_LOAD,RESERVATION_PER_SERVER,TOP_TO_BOTTOM,ROUND_ROBIN,1,LOW_LOAD,TOP_TO_BOTTOM,NaN,NaN,NaN,NaN,NaN

,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,B,instance-medium-15,223860.449368,912.341,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,BOTTOM_TO_TOP,ROUND_ROBIN,RANDOM,NaN
1,B,instance-medium-25,12782.286877,47.363,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,TOP_TO_BOTTOM,ROUND_ROBIN,ROUND_ROBIN,NaN
2,B,instance-small-17,5477.246625,55.715,50,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,TOP_TO_BOTTOM,IGNORE_TREE_LEVEL,HIGH_LOAD,ROUND_ROBIN,NaN
3,B,instance-small-19,545.051658,2.604,50,NaN,NaN,NaN,NaN,NaN,1,NaN,NaN,TOP_TO_BOTTOM,IGNORE_TREE_LEVEL,HIGH_LOAD,LOW_LOAD,NaN

11088,algorithm,instance,value,time,capacity,linkedSpaceDistribution,alreadyLinkedDistribution,reservationType,alreadyLinkedTreeTraversal,publisherServerSelectionDistribution,maxReservation,viewerAndLinkFromDistribution,linkedSpaceTreeTraversal,viewerServerSelectionTreeTraversal,newViewerServerParentSelectionTreeTraversal,newViewerServerParentSelectionDistribution,viewerServerSelectionDistribution,viewerServerSelectionOption
0,A,instance-small-19,544.553175,0.374,50,NaN,NaN,NaN,NaN,NaN,<NA>,NaN,NaN,NaN,NaN,NaN,NaN,HIGH_LOAD